artifacts_root: articats

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sazidrj/Data/raw/main/samsum-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion